/**
 * Weekly Report Email
 *
 * Sent on Sunday after a user's WeeklyAnalytics record is generated by
 * build-weekly-analytics. Notifies them their report is ready, shows a few
 * teaser highlights, and deep-links to the in-app report.
 */

import { UserProfile } from "../user/types";
import { WeeklyAnalytics } from "../analytics/types";
import {
  sendEmail,
  buildEmailFooterHtml,
  buildEmailFooterText,
  getAppUrl,
  SendEmailResult,
} from "../email-utils";
import { logger } from "../logger";

const MONTH_ABBREVIATIONS = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];

/**
 * Format an ISO date string (YYYY-MM-DD) as "MMM D" using UTC parts so the
 * label matches the ISO week boundaries used by the analytics generator.
 */
function formatMonthDayUtc(isoDate: string): string {
  const date = new Date(`${isoDate}T00:00:00Z`);
  return `${MONTH_ABBREVIATIONS[date.getUTCMonth()]} ${date.getUTCDate()}`;
}

function formatTonnage(value: number, unitSystem: string | undefined): string {
  const rounded = Math.round(value).toLocaleString("en-US");
  const unit = unitSystem === "metric" ? "kg" : "lbs";
  return `${rounded} ${unit}`;
}

function firstSentence(text: string, maxChars = 180): string | null {
  if (!text) return null;
  const trimmed = text.trim();
  if (!trimmed) return null;

  const sentenceEnd = trimmed.search(/[.!?](\s|$)/);
  const candidate =
    sentenceEnd >= 0 ? trimmed.slice(0, sentenceEnd + 1) : trimmed;

  if (candidate.length <= maxChars) return candidate;
  return `${candidate.slice(0, maxChars - 1).trimEnd()}…`;
}

function buildReportUrl(
  userId: string,
  weekId: string,
  coachId: string | null,
): string {
  const base = `${getAppUrl()}/training-grounds/reports/weekly?userId=${encodeURIComponent(userId)}&weekId=${encodeURIComponent(weekId)}`;
  return coachId ? `${base}&coachId=${encodeURIComponent(coachId)}` : base;
}

/**
 * Send a weekly report notification email to a user whose WeeklyAnalytics
 * record was just generated.
 */
export async function sendWeeklyReportEmail(
  user: UserProfile,
  analytics: WeeklyAnalytics,
  coachId: string | null,
): Promise<SendEmailResult> {
  const firstName = user.firstName || user.username;
  const reportUrl = buildReportUrl(user.userId, analytics.weekId, coachId);
  const weekRange = `${formatMonthDayUtc(analytics.weekStart)} – ${formatMonthDayUtc(analytics.weekEnd)}`;

  const structured = analytics.analyticsData?.structured_analytics ?? {};
  const sessions = structured.metadata?.sessions_completed;
  const tonnage = structured.volume_breakdown?.working_sets?.total_tonnage;
  const overload = structured.weekly_progression?.progressive_overload_score;
  const narrative = firstSentence(analytics.analyticsData?.human_summary);

  const highlights: string[] = [];
  if (typeof sessions === "number" && sessions > 0) {
    highlights.push(
      `<strong>${sessions}</strong> workout${sessions === 1 ? "" : "s"} logged`,
    );
  }
  if (typeof tonnage === "number" && tonnage > 0) {
    highlights.push(
      `<strong>${formatTonnage(tonnage, user.preferences?.unitSystem)}</strong> total tonnage moved`,
    );
  }
  if (typeof overload === "number" && overload > 0) {
    const score = Number.isInteger(overload) ? overload : overload.toFixed(1);
    highlights.push(
      `<strong>${score}/10</strong> progressive overload score`,
    );
  }

  const highlightsHtml =
    highlights.length > 0
      ? highlights.map((line) => `<p style="margin: 6px 0;">• ${line}</p>`).join("")
      : `<p style="margin: 0;">Your weekly summary is ready inside.</p>`;

  const narrativeHtml = narrative
    ? `<p style="font-style: italic; color: #555;">${narrative}</p>`
    : "";

  const htmlBody = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Your NeonPanda Weekly Report Is Ready</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style>
    body {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', sans-serif;
      line-height: 1.6;
      color: #333;
      margin: 0;
      padding: 0;
      background-color: #f9f9f9;
      font-size: 16px;
    }
    p {
      font-size: 16px;
      margin: 15px 0;
      color: #333;
    }
    .email-wrapper {
      width: 100%;
      background-color: #f9f9f9;
      padding: 20px 0;
    }
    .container {
      max-width: 600px;
      margin: 0 auto;
      background-color: #ffffff;
      border-radius: 8px;
      padding: 30px;
      box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
    }
    .logo-header {
      background-color: #0a0a0a;
      padding: 10px;
      margin: -30px -30px 30px -30px;
      border-radius: 8px 8px 0 0;
      text-align: center;
    }
    .logo-header img {
      max-width: 400px;
      height: auto;
    }
    h1 {
      color: #ff6ec7;
      font-size: 28px;
      margin-bottom: 20px;
      margin-top: 0;
    }
    .feature-box {
      background-color: #fff5f8;
      border-left: 4px solid #FF10F0;
      padding: 15px;
      margin: 20px 0;
      border-radius: 4px;
    }
    .feature-box h2 {
      color: #FF10F0;
      margin-top: 0;
      font-size: 18px;
      margin-bottom: 10px;
    }
    .feature-box p {
      color: #333;
      margin: 0;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e0e0e0;
      font-size: 14px;
      color: #666;
    }
    .footer p {
      margin: 10px 0;
    }
    .footer a {
      color: #00ffff;
      text-decoration: none;
    }
  </style>
</head>
<body>
  <div class="email-wrapper">
    <div class="container">
      <div class="logo-header">
        <img src="https://neonpanda.ai/images/logo-dark-sm.webp" alt="NeonPanda Logo">
      </div>

      <h1>Hey ${firstName}! 📊</h1>

      <p>Your weekly training report for <strong>${weekRange}</strong> is ready. Your coach pulled it together from everything you logged this week.</p>

      <div class="feature-box">
        <h2>📈 This Week at a Glance</h2>
        ${highlightsHtml}
      </div>

      ${narrativeHtml}

      <p>Tap below to see the full breakdown – volume by movement, progression, recovery signals, and your coach's read on what's working.</p>

      <p style="text-align: center; margin: 30px 0;">
        <a href="${reportUrl}" style="display: inline-block; background-color: #FF10F0; color: #ffffff; padding: 14px 32px; border-radius: 6px; font-weight: 600; font-size: 16px; text-decoration: none; font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;">
          View Your Full Report
        </a>
      </p>

      <p style="margin-top: 30px; font-style: italic; color: #333;">– The NeonPanda Team</p>

${buildEmailFooterHtml(user.email, "weekly", user.userId)}
    </div>
  </div>
</body>
</html>
  `.trim();

  const highlightsText =
    highlights.length > 0
      ? highlights
          .map((line) => `  • ${line.replace(/<\/?strong>/g, "")}`)
          .join("\n")
      : "  Your weekly summary is ready inside.";

  const narrativeText = narrative ? `\n${narrative}\n` : "";

  const textBody = `
Hey ${firstName}! 📊

Your weekly training report for ${weekRange} is ready. Your coach pulled it together from everything you logged this week.

📈 This Week at a Glance:
${highlightsText}
${narrativeText}
Tap below to see the full breakdown – volume by movement, progression, recovery signals, and your coach's read on what's working.

View your full report: ${reportUrl}

– The NeonPanda Team

Visit NeonPanda: ${getAppUrl()}
${buildEmailFooterText(user.email, "weekly", user.userId)}
  `.trim();

  const result = await sendEmail({
    to: user.email,
    subject: `NeonPanda - ${firstName}, your weekly report is ready`,
    htmlBody,
    textBody,
  });

  if (result.success) {
    logger.info(`✅ Successfully sent weekly report email to ${user.email}`, {
      messageId: result.messageId,
      requestId: result.requestId,
      userId: user.userId,
      weekId: analytics.weekId,
    });
  } else {
    logger.warn(`❌ Failed to send weekly report email to ${user.email}`, {
      userId: user.userId,
      weekId: analytics.weekId,
      error: result.error?.message,
    });
  }

  return result;
}
