import { containerPatterns } from "../../utils/ui/uiPatterns";
import { SparklesIcon } from "../highlights/icons";

export default function AiGeneratedBadge({ description }) {
  return (
    <div className={containerPatterns.aiAttributionBadgeWrapper}>
      <div className={containerPatterns.aiAttributionBadgeInner}>
        <SparklesIcon className="w-4 h-4 text-synthwave-neon-cyan drop-shadow-[0_0_6px_#00ffff] shrink-0 mt-0.5" />
        <span className="font-body text-sm leading-relaxed">
          <span className="text-synthwave-neon-cyan font-medium">
            Generated by AI
          </span>
          {description ? (
            <span className="text-synthwave-text-secondary"> • {description}</span>
          ) : null}
        </span>
      </div>
    </div>
  );
}
