/**
 * Tool framework types. Tools are produced by `defineTool` (Zod-backed)
 * or by `adaptLegacyTool` (wraps the existing v1 `Tool<TCtx>` shape so the
 * v2 runtime can host both during migration).
 *
 * Phase 1 — see plan §2.
 */

import type { AgentContext } from "../../types";

/* -------------------------------------------------------------------------- */
/*                              Result envelopes                              */
/* -------------------------------------------------------------------------- */

export type ToolErrorCode =
  | "timeout"
  | "tool_output_invalid"
  | "tool_input_invalid"
  | "tool_blocked"
  | "tool_not_found"
  | "downstream_lambda_failed"
  | "transient"
  | "permanent"
  | "human_input_required";

export type ToolSuccess<T> = {
  ok: true;
  data: T;
  /** Concise summary surfaced in logs / metrics. Optional. */
  summary?: string;
  /** When set, replaces the full data when serialising the tool result back
   *  into Bedrock conversation history. Used to keep histories lean. */
  conversationSummary?: unknown;
  /** When set, the agent stores `data` under this key in the result store
   *  (overrides the default tool-id / alias mapping). */
  toolStoreKey?: string;
  /** When set, store the result at this index in the keyed array (used by
   *  workout-logger array semantics). */
  toolStoreIndex?: number;
};

export type ToolFailure = {
  ok: false;
  code: Exclude<ToolErrorCode, "human_input_required">;
  message: string;
  retryable: boolean;
  details?: unknown;
};

export type ToolHumanInputRequired = {
  ok: false;
  code: "human_input_required";
  prompt: string;
  resumeToken: string;
  suggestedReplies?: string[];
};

export type ToolResult<T = unknown> =
  | ToolSuccess<T>
  | ToolFailure
  | ToolHumanInputRequired;

/* -------------------------------------------------------------------------- */
/*                          Execution context + middleware                    */
/* -------------------------------------------------------------------------- */

export interface ToolExecutionContext<TContext extends AgentContext> {
  /** Domain-supplied context (userId, coach config, etc.). */
  agentContext: TContext;
  /** Shared per-run keyed result store. */
  resultStore: ToolResultStoreLike;
  /** Bedrock-supplied identifier for this tool call. */
  toolUseId: string;
  /** Aborts when the tool's `timeoutMs` elapses. Tool authors should pass
   *  this through to long-running calls (fetch, AWS SDK, etc.). */
  signal: AbortSignal;
  /** Iteration the tool fires in (1-indexed). */
  iteration: number;
}

export interface ToolMiddleware<TContext extends AgentContext> {
  /** Runs after input validation, before the tool's execute. Throw to abort
   *  the call (the agent treats this as a `tool_blocked` failure). */
  before?: (
    input: unknown,
    ctx: ToolExecutionContext<TContext>,
  ) => Promise<void> | void;
  after?: (
    input: unknown,
    result: ToolResult<unknown>,
    ctx: ToolExecutionContext<TContext>,
  ) => Promise<void> | void;
  onError?: (
    input: unknown,
    error: unknown,
    ctx: ToolExecutionContext<TContext>,
  ) => Promise<void> | void;
}

/** Minimal interface the scheduler needs from a result store, broken out so
 *  tool-types.ts has no dependency on the store implementation. */
export interface ToolResultStoreLike {
  put(toolId: string, result: unknown, opts?: { index?: number; uniqueKey?: string }): void;
  get<T = unknown>(key: string, index?: number): T | undefined;
  getAll<T = unknown>(key: string): T[] | undefined;
  has(key: string): boolean;
}

/* -------------------------------------------------------------------------- */
/*                              The Tool itself                               */
/* -------------------------------------------------------------------------- */

export type ToolValidator<T> = (
  value: unknown,
) => { ok: true; value: T } | { ok: false; error: string };

export interface Tool<TContext extends AgentContext = AgentContext, TIn = any, TOut = any> {
  id: string;
  description: string;
  /** JSON Schema fragment passed to Bedrock toolConfig. Auto-generated by
   *  `defineTool` from the Zod input schema. */
  inputSchema: Record<string, unknown>;
  /** Optional output schema fragment, used by validateOutput. */
  outputSchema?: Record<string, unknown>;
  /** Free-text status messages the streaming runtime may surface while the
   *  tool is running. */
  contextualMessages?: string[];
  /** Hard timeout in milliseconds. Default 25_000. */
  timeoutMs: number;
  /** When true, a tool may run concurrently with other parallel-safe tools
   *  in the same iteration. Default false. */
  parallelSafe: boolean;
  /** Whether transient failures are retryable by the framework. Default true. */
  retryable: boolean;
  /** When true, tool input is omitted from `ToolCallRecord` and the SSE event
   *  payload (sensitive tools like `save_memory`, `apply_workout_edits`). */
  redactInput: boolean;
  middleware: ToolMiddleware<TContext>[];
  execute: (
    input: TIn,
    ctx: ToolExecutionContext<TContext>,
  ) => Promise<ToolResult<TOut>>;
  validateInput: ToolValidator<TIn>;
  validateOutput?: ToolValidator<TOut>;
  /**
   * Optional callback that decides where in the result store this tool's
   * output should be persisted. Called for every put path (success,
   * returned failure, blocked-by-policy, throw-from-execute) so the
   * placement is consistent regardless of how the call resolved. Returns
   * `{ index?, uniqueKey? }` — same options as `ToolResultStore.put`.
   * When undefined (the default) the scheduler falls back to alias-key
   * replace semantics. Workout-logger uses this for its multi-workout
   * positional storage; coach-creator and program-designer don't need it
   * (single-call alias storage / dedicated middleware respectively).
   *
   * Per-result `toolStoreIndex` / `toolStoreKey` on a `ToolSuccess`
   * envelope still take precedence over this callback's value, so a
   * tool's `execute` can override the per-tool default for individual
   * calls.
   */
  getStoreLocation?: (
    input: TIn,
    ctx: ToolExecutionContext<TContext>,
  ) => { index?: number; uniqueKey?: string };
}

/* -------------------------------------------------------------------------- */
/*                       UI-facing tool-call record                           */
/* -------------------------------------------------------------------------- */

export interface ToolCallRecord {
  toolUseId: string;
  toolName: string;
  status: "running" | "complete" | "error";
  /** Iteration the call started in. */
  iteration: number;
  /** Position in `fullResponseText` where the call was anchored when emitted.
   *  Lets the frontend interleave tool blocks with assistant text. */
  contentOffset: number;
  startedAtMs: number;
  durationMs?: number;
  /** Omitted when the tool sets `redactInput: true`. */
  toolInput?: unknown;
  /** Concise summary of the result, only set for completed calls. */
  resultSummary?: string;
  errorMessage?: string;
  errorCode?: ToolErrorCode;
}
